export const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEMS_TO_CART  : 'ADD_ITEMS_TO_CART',
    REMOVE_ITEMS : 'REMOVE_ITEMS',
    DELETE_ITEM_FROM_CART : 'DELETE_ITEM_FROM_CART'
} 